import { Roboto } from 'next/font/google'
import "./globals.css";
import Navbar from "@/components/NavBar";

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${roboto.className}  h-full antialiased`}
    >
     <body>
  <Navbar />

  <div className="md:pl-60">
    <main className="mx-auto w-full max-w-5xl px-4 py-6 pb-24 sm:px-6 md:pb-8">
      {children}
    </main>
  </div>
</body>
    </html>
  );
}
